### ISSUE TITLE
Order Confirmed Screen: Full Address out of order

### ISSUE THREAD

**Issue by siegel86** [DrivingThru/DrivingThruiOS#105]
![Image-1](https://user-images.githubusercontent.com/42547181/55263034-04db5600-522d-11e9-89a1-aa74f0326708.jpg)

**Comment by danipralea** [comment]
@siegel86 back in issue #84 you asked for the full address in this screen (previously it was just street and number. Please provide further clarification as to what format you want the address to be in and what specific parts of the address should be displayed.

**Comment by kevinp** [comment]
@danipralea 

[Street Number] [Street Name] [Suite Number], [City], [State] [Zip]

**Comment by kevinp** [comment]
30895 Thousands Oaks Blvd #101, Westlake Village, CA 91362
