### ISSUE TITLE
Restaurant Menu

### ISSUE THREAD

**Issue by siegel86** [DrivingThru/DrivingThruiOS#116]
Full menu and pricing needs to be inserted

**Comment by siegel86** [comment]
Team - please advise if adding a full menu is too time consuming for the mvp.  If it is then we can lean out the menu offerings for now.

**Comment by vfxdrummer** [comment]
@siegel86, gonna assign this to @davingee to get him started. Do we have a menu to transcribe?
Full is fine, whatever you want.
