### ISSUE TITLE
Tablet set up:  Consensus on which iPad version is needed for test site #1 

### ISSUE THREAD

**Issue by siegel86** [DrivingThru/DrivingThruiOS#118]
1.  What iPad version do we need to support the app?
2.  Would a used version suffice? 
3.  How do we strip down whichever device we use so it is a single application that only operates the DT vendor dashboard?
4.  How do we set up that tablet?   Via TestFlight or a different method?

**Comment by kevinp** [comment]
@siegel86 , 
1. A recent used one is fine.  
1. [Here is how to lock it down ](https://www.webascender.com/blog/setup-kiosk-mode-lock-ipad-just-one-app/)
1. Let's set it up with TestFlight for now.

**Comment by siegel86** [comment]
@vfxdrummer @danipralea - do you know what minimum version is required?
