### ISSUE TITLE
Creating Account:   'Create Account' button isn't working 

### ISSUE THREAD

**Issue by siegel86** [DrivingThru/DrivingThruiOS#122]
1.   I fill in my name/email/etc
2.   I type in password and verify
3.  I press 'create account' and the screen doesn't change.

**Comment by danipralea** [comment]
I didn't manage to recreate the issue, could you please provide some steps to recreate this?

**Comment by siegel86** [comment]
I press create account and the button isnt registering (i tried to send video but this site won't accept that file type).  
![IMG_3884](https://user-images.githubusercontent.com/42547181/55505608-535f6a80-5608-11e9-99ae-164aaef1768a.JPG)

**Comment by siegel86** [comment]
@vfxdrummer I tried creating a new account from my phone under a different name and it is still not letting me through.  I also tried from my ipad and when i click create account it doesn't let me pass.
