### ISSUE TITLE
Arrival geofence/push notification adjustments  

### ISSUE THREAD

**Issue by siegel86** [DrivingThru/DrivingThruiOS#149]
![IMG_4300](https://user-images.githubusercontent.com/42547181/57813972-ecfd5a00-7726-11e9-9b37-b7dab9f8f928.JPG)
1.   screen shot represents simulation to Aaron's house.
2a.  I am 3 min/.7 miles away and i got the push notification that i am in the Vendor area.  
2b.  Can we change the wording of that notification to read:
                 "You are approaching the Pick Up Area!
                   Please return to the app for instructions."
3.  Ideally that appears when you are approaching the red zone.  For example in the vicinity of this location...call it within 500sf:
![IMG_4301](https://user-images.githubusercontent.com/42547181/57814063-5b421c80-7727-11e9-849d-ac37e95b9669.JPG)
4.  Ideally that push notification drop stays longer (right now it is like 2 seconds) so the customer has the ability to press it to take them back to the app?
5.  So when they go back to the app they will get the pop up described in issue #147 (ie either they've arrived but are outside the parking zone or they've arrived are are in the red parking zone and can press Im Parked

**Comment by siegel86** [comment]
![IMG_4304](https://user-images.githubusercontent.com/42547181/57814846-e6241680-7729-11e9-8836-629cd9858edf.JPG)
1.  Screenshot represents simulation to Scott's house
2.  I didn't use navigation and instead stayed in the in-app map
3.  It recognized my arrival when i was about the same distance away as referenced in the example to Aarons House...abt 2-3 min and 1 mile away.

**Comment by vfxdrummer** [comment]
I just looked and Aaron's deliveryDistanceMax was set to 1000, that's why it triggered so far away.
I don't think that this is an issue w/ appropriate values.

**Comment by vfxdrummer** [comment]
"Ideally that push notification drop stays longer (right now it is like 2 seconds) so the customer has the ability to press it to take them back to the app?"

We can't control this, it's built into iOS.
