### ISSUE TITLE
New User Flow: Create Sign-Up / Registration Flow

### ISSUE THREAD

**Issue by vfxdrummer** [DrivingThru/DrivingThruiOS#51]
The app utilizes FirebaseUI for authentication.
It needs a custom UI built for sign-up.

See the following for docs on how to customize :
https://firebase.google.com/docs/auth/ios/firebaseui
https://www.youtube.com/watch?v=d_byFfP3cTw

Please see the new screens from Yurri :
https://sketch.cloud/s/G9xrb

**Comment by kevinp** [comment]
@danipralea  , I'm pretty sure this is complete.  Would you please close unless there are other issues we should open in response?
