### ISSUE TITLE
Vendor App: Settings screen

### ISSUE THREAD

**Issue by vfxdrummer** [DrivingThru/DrivingThruiOS#54]
The Vendor app needs edit functionality, so that an employee can edit hours available, among other things. See prototype app for details :
https://share.proto.io/NEKNAT/

**Comment by kevinp** [comment]
@yuriisekretar , designs complete?

**Comment by danipralea** [comment]
@kevinp @yuriisekretar is the settings screen design/flow finalised?
I need to know this in order to give my estimation for a connex tax I have for this (#87 )

**Comment by siegel86** [comment]
@vfxdrummer is this completed?
