### ISSUE TITLE
Notifications: driver has arrived

### ISSUE THREAD

**Issue by vfxdrummer** [DrivingThru/DrivingThruiOS#58]

**Comment by kevinp** [comment]
Related to #59 

@siegel86 , what is the content of the message?

**Comment by siegel86** [comment]
@vfxdrummer @kevinp Tim was the originator...Tim has this been resolved?

**Comment by kevinp** [comment]
@siegel86 , I was speaking to the content of the message, what does it say exactly.  "Scott has arrived"... "Order 11 has arrived"... , etc.  I've added #85 , which should track the content for all screens.

**Comment by siegel86** [comment]
merged into #56
