### ISSUE TITLE
Push Notifications: Setup Firebase Cloud Messaging Pattern

### ISSUE THREAD

**Issue by vfxdrummer** [DrivingThru/DrivingThruiOS#59]
Push notifications need to be triggered by the server using FCM :

https://firebase.google.com/docs/cloud-messaging/
https://firebase.google.com/docs/functions/use-cases
https://medium.com/yale-sandbox/react-native-push-notifications-with-firebase-cloud-functions-74b832d45386
https://medium.com/@jerinamathews/send-firebase-cloud-messaging-fcm-to-a-topic-using-cloud-function-when-realtime-database-value-fa78fa758549

**Comment by kevinp** [comment]
@vfxdrummer , would you please document which push notifications these are?
1. Order accepted and in process
1. Order cancelled (hopefully not)
??

@siegel86, please add to this list as necessary.  We'll decide what we need for the initial email invitation

**Comment by siegel86** [comment]
@kevinp Im not clear on what/where i should be adding... list of emails? and/or content for email invitation?

**Comment by kevinp** [comment]
@siegel86 , in the respective issues.  So go to that specific issue and just copy/paste, add links to external documents, etc.

**Comment by danipralea** [comment]
@vfxdrummer are you doing this?

**Comment by danipralea** [comment]
Also, I want to mention that the setup for Firebase Functions is already done.
