### ISSUE TITLE
Permissions Flow:  Screen transitions

### ISSUE THREAD

**Issue by siegel86** [DrivingThru/DrivingThruiOS#67]
After I select Allow, not allow etc, can we make it so it takes you to the next screen vs now where when I make that selection it keeps me at that same screen and i have to swipe to the next.    Also on all these screens, what happens if i click "No Thanks".

**Comment by kevinp** [comment]
I believe this is resolved?

**Comment by kevinp** [comment]
@danipralea , also when you make a commit related to an issue..  would you please add the issue to the commit?

**Comment by kevinp** [comment]
Also please see #66
