### ISSUE TITLE
Restaurant List:  Missing distance and time to location

### ISSUE THREAD

**Issue by siegel86** [DrivingThru/DrivingThruiOS#69]
The miles distance/time to distance is miss
![Image-1](https://user-images.githubusercontent.com/42547181/54628082-04bfa700-4a32-11e9-810b-defc140ef374.jpg)
ing

**Comment by danipralea** [comment]
This is a no issue. We agreeed on not showing the distance for after the release. Are we going back on that?

**Comment by siegel86** [comment]
I am not sure when we went away from that but yes in the initial screen with all the restaurants (right now just Dunkin) there should be a time/distance box.  This will be the first glance for customers to see how far away they are from the restaurant.  If it is too much engineering to put in both miles and time then I am okay with just time.  As they work their way through the order and check out that time will be refined but this is a pretty important feature to have upfront.

**Comment by kevinp** [comment]
@danipralea , can you provide an estimate of effort on this?

**Comment by siegel86** [comment]
merged w #68
