### ISSUE TITLE
Events:  Please identify key events (of business value) in the customer journey

### ISSUE THREAD

**Issue by kevinp** [DrivingThru/DrivingThruiOS#74]
1. User clicks on campaign
1. User downloads app
1. User provides email
1. User completes on-boarding screens
1. User completes first order
1. Customer arrives at restaurant
1. Customer receives order
1. Customer reviews order
...

**Comment by siegel86** [comment]
User clicks on campaign
User downloads app
User provides email
User completes on-boarding screens
USER SELECTS RESTAURANT
User completes first order
CUSTOMER NAVIGATES TO RESTAURANT
Customer arrives at restaurant
Customer receives order
Customer reviews order

**Comment by siegel86** [comment]
2 were added in the sequence in all caps

**Comment by kevinp** [comment]
Closed and put the results in #76 .
