### ISSUE TITLE
DevOps Analytics: Implement to track Crashes, Exceptions, Performance, etc.

### ISSUE THREAD

**Issue by kevinp** [DrivingThru/DrivingThruiOS#80]
Crashlytics?

**Comment by vfxdrummer** [comment]
Setting up Crashlytics, which is now conveniently owned by Firebase :
https://firebase.google.com/docs/crashlytics/

**Comment by kevinp** [comment]
@vfxdrummer , would you please update title with estimate of effort in hours.. something like (6, 2, 4)  - ie hours estimated, hours worked, hours remaining.  Thanks!

**Comment by vfxdrummer** [comment]
I set up Crashlytics in Firebase. However, it i only showing up on the dashboard for the Vendor app and not the client. It feels like a bug in Firebase where it's only working for one app in the project. 
I have an issue open with support.

**Comment by vfxdrummer** [comment]
0 hours left, just waiting for Firebase to tell me why we can't see the dashboard for Client, and only Vendor. Could be a bug on their side or something with the setup. Just followed up with support.

**Comment by vfxdrummer** [comment]
Support got back to me. They said that there should be now problem running 2 different apps in one Firebase Projects and seeing Crashlytics Dashboards for each. They gave me instructions on capturing some console output to send to them. Doing so now.
