### ISSUE TITLE
Content Edit:  Review all screens for A. needed content  B. edit/finalize content

### ISSUE THREAD

**Issue by kevinp** [DrivingThru/DrivingThruiOS#85]
Outcome should be a list of content updates/edits by screen.

**Comment by siegel86** [comment]
Instead of Order #1, 2... can we change on the main screen to link up with "First Name, Car Make/Model".  So the store worker can glance at screen and see "Scott/Toyota/Tundra".  
![IMG_0250](https://user-images.githubusercontent.com/42547181/54873221-133df380-4d8f-11e9-9120-1fe01925aa8c.jpg)
Then when that customer arrives and hits Im parked, it will state "Scott/Toyota/Tundra has arrived"

**Comment by siegel86** [comment]
Complete Menu needs to be uploaded

**Comment by siegel86** [comment]
In menu item, the "Instructions" box should be changed to "Special Instructions"

**Comment by danipralea** [comment]
@siegel86 @kevinp  is this a proposition or is it final?
I can do pretty much everything, but I need to know it's agreed/decided by you guys first. don't wanna work twice 😄

**Comment by kevinp** [comment]
@danipralea , if the task is assigned to somebody else please assume it is in process.  Once we assign to you then we need your help with it.

**Comment by siegel86** [comment]
Sign in Screen - Email Address is misspelled.   Also need to change "Create an Account" to "Create Account"

**Comment by siegel86** [comment]
Sign in Screen - change "Create an Account" to "Create Account"

**Comment by siegel86** [comment]
Create Account screen - Email Address is misspelled.

**Comment by siegel86** [comment]
Create Account screen - add logic that indicates phone is optional and all other fields are required.  If they press create account without filling out all required screens then it will highlight which screens are needed to proceed.

**Comment by siegel86** [comment]
Create Account screen - format each line so each user is promoted to enter data consistently.  ie First Name - first initial capitalized... same with last name.   phone in 888-888-8888 format.  etc.

**Comment by siegel86** [comment]
@siegel86 to go through full process of creating account and onboarding (will need to have my previous account cleared so i can start from beginning)
