### ISSUE TITLE
Tablet main screen:  Implement remaining features

### ISSUE THREAD

**Issue by siegel86** [DrivingThru/DrivingThruiOS#86]
How many hours to finish tablet?

**Comment by kevinp** [comment]
@siegel86 , it would be helpful if you would identify missing features.  List them here.

@danipralea , would you please estimate

**Comment by danipralea** [comment]
@siegel86 @kevinp we need clarifications for the tasks that are currently pending/idle/need additional information first, in order to be able to estimate everything.

**Comment by danipralea** [comment]
Missing features list for Vendor app:
 - archived orders
 - order settings
 - add all user details (currently only the name is displayed because that’s the only available info in database)
 - replacing order number with user infos
 - sending the user location from client app and display it in the vendor app

**Comment by kevinp** [comment]
@danipralea , would you please add rough estimates for the features listed below?  If we need to break out into separate issues we can do so.  

It sounds like this should be priority:
1. Persist user details (first name, email, phone, car make/model) to the database
1. Replace order number with user details as mentioned in #85 
1. Send the user location from client app and display it in the vendor app.

**Comment by danipralea** [comment]
Here's the rough estimated:
1. (2, 1, 1)
2. (1, 0, 1)
3. (5, 0 , 5)

**Comment by kevinp** [comment]
Perfect.  Thanks @danipralea .  If you have time today, let's start on 3.  I'll split it out as a separate issue.  I'll be speaking with Scott tonight and we'll be further prioritizing the project board so that we can have a sprint meeting all together.
