### ISSUE TITLE
Tablet setting screen:  Implement (8, 5, 3)

### ISSUE THREAD

**Issue by siegel86** [DrivingThru/DrivingThruiOS#87]
How many hours to complete the settings screen on the tablet?

**Comment by kevinp** [comment]
@danipralea , would you please add estimate to the title of this issue?

**Comment by danipralea** [comment]
same as #86

**Comment by siegel86** [comment]
@danipralea can you estimate for the settings screen?

**Comment by danipralea** [comment]
So far, only the Update Prep Time is done. I am now working on delivery max distance. Then fixing bugs and inconsistencies.
