### ISSUE TITLE
Customer Profile:  Implement

### ISSUE THREAD

**Issue by siegel86** [DrivingThru/DrivingThruiOS#88]
Determine hours to complete the IOS Profile screen and related onboarding components.  
![Image-1](https://user-images.githubusercontent.com/42547181/54885486-cf53f880-4e39-11e9-8271-f76ec7dbda74.jpg)

**Comment by kevinp** [comment]
@danipralea , would you please add an estimate to the title of this issue?  (6, 0, 6) where the numbers represent (estimated hours, hours spent so far, hours remaining)
