### ISSUE TITLE
Order Confirmed: Destination Marker missing on map?

### ISSUE THREAD

**Issue by siegel86** [DrivingThru/DrivingThruiOS#90]
![Image-1](https://user-images.githubusercontent.com/42547181/54885698-69b53b80-4e3c-11e9-999d-efc0405b4c76.jpg)

**Comment by kevinp** [comment]
@danipralea , @vfxdrummer , I believe @siegel86 means we're missing the destination marker / pin?

**Comment by siegel86** [comment]
This feature:
![IMG_3829](https://user-images.githubusercontent.com/42547181/54933713-6a9caa80-4eda-11e9-832e-cec028382f10.jpg)

**Comment by siegel86** [comment]
![IMG_3837](https://user-images.githubusercontent.com/42547181/54943488-a0e42500-4eee-11e9-832c-72dc0b8b69be.PNG)
Parking zone also missing once customer arrives.

**Comment by siegel86** [comment]
I am assigning to @davingee. @vfxdrummer if you think he will need guidance, please chime in.
