### ISSUE TITLE
Order Screen:   Compress graphics section on top so that controls aren't hidden

### ISSUE THREAD

**Issue by siegel86** [DrivingThru/DrivingThruiOS#91]
Pull up screen so it is intuative to scroll below the size to find add ons/special instructions
![Image-1](https://user-images.githubusercontent.com/42547181/54885850-180db080-4e3e-11e9-9fff-8e07ef24e818.jpg)

**Comment by danipralea** [comment]
Can you please develop on this one @siegel86 ?
