### ISSUE TITLE
Orders:  screen sticks when after adding special instructions

### ISSUE THREAD

**Issue by siegel86** [DrivingThru/DrivingThruiOS#94]
(I can't send picture to demo so will do best to type the issue).   

1. Order a large coffee and type in the special instructions box 
1. Add cream/sugar for example. 
1. I click "add to order" and it goes to my cart.   

Issue is when i try and scroll back to the top it wont let me get past this point:
![Image-1](https://user-images.githubusercontent.com/42547181/54937661-11d11000-4ee2-11e9-8698-ad35837cb71e.jpg)

After playing around i see you have to hit the grayed out "Add to Order" box again to activate the screen to allow you back up... but is there a way to just allow the customer to thumb their way up.   This could become a point of frustration.

**Comment by kevinp** [comment]
@danipralea , please estimate
