### ISSUE TITLE
Drive times: Time between tablet and phone are not the same.

### ISSUE THREAD

**Issue by siegel86** [DrivingThru/DrivingThruiOS#95]
To reproduce:

1. I have both vendor app and phone up at the same time
1. I order on the phone
1. I see Order Confirmed screen with drive time and pickup time (10:05 and 19 minutes)
1. I look at the tablet, and the order shows as 38 minutes away (are we doubling the 19 minutes?)

![InkedIMG_3834_LI](https://user-images.githubusercontent.com/42547181/54940798-b0f90600-4ee8-11e9-8eb6-f87950c1e4d2.jpg)
![InkedIMG_0251_LI](https://user-images.githubusercontent.com/42547181/54940809-b48c8d00-4ee8-11e9-8c86-28f33663c70e.jpg)

Then as i drive the times are still not in sync:
phone time vs tablet time...
![InkedIMG_3835_LI](https://user-images.githubusercontent.com/42547181/54940986-07664480-4ee9-11e9-84d1-f077ee4f8e99.jpg)
![InkedIMG_0252_LI](https://user-images.githubusercontent.com/42547181/54941045-27960380-4ee9-11e9-9947-ce04e8406416.jpg)

**Comment by siegel86** [comment]
Please note a key feature to be correctly implemented... if I place my order and my driving distance is within  the restaruants meal prep time, the "estimated drive time" should be whatver the actual navigation time is and the "your order will be ready" time should be the mimimum prep time.
![IMG_3840](https://user-images.githubusercontent.com/42547181/54941603-7d1ee000-4eea-11e9-82ed-557fcfc0a35c.jpg)
This picture simulates me placing an order while actually park inside the Dunkin parking lot.   The drive time shoudl be 0 and the time my order is ready is whatever minimum time the restaurant determines either in the setting or this screen, which in this example is 5 minutes:
![IMG_0255](https://user-images.githubusercontent.com/42547181/54941903-34b3f200-4eeb-11e9-8bbe-9093e1d434f7.jpg)

**Comment by siegel86** [comment]
@vfxdrummer - can you weigh in on some the navigation issues mentioned above?

**Comment by siegel86** [comment]
![IMG_0260](https://user-images.githubusercontent.com/42547181/55264353-44a43c80-5231-11e9-881a-4e5fc3a78b77.PNG)
![IMG_3855](https://user-images.githubusercontent.com/42547181/55264354-44a43c80-5231-11e9-9fd6-239807aadc7a.JPG)

Is it feasible for the "minutes away" time on the tablet to be synchronized with the the drive time provided  by the navigation?   In the attached example, the tablet didn't sync until I arrived into the arrival geofence.  While driving, GPS was counting down as represented by the 1 minute but the tablet stayed on 2 minutes (the order originated from 2 minutes away).

**Comment by vfxdrummer** [comment]
Hey Guys -

I picked up this ticket. I am taking a look.

**Comment by vfxdrummer** [comment]
So, the client should be using it's location and the that of the vendor to continuously compute "distance to" and an "eta" w/ MKDirections. This is streamed to Firebase in realtime, updating as you go. The Vendor App continuously listens to these updates and updated the display. 
This could be an issue with the formula used to calculate the time on the Vendor App.
Not sure, I am looking into the code, now. We'll get it sorted.

**Comment by vfxdrummer** [comment]
Ok. I am simulating an order with my location set to Scott's House to start.
Most everything looks good, it shows at ETA of 16 minutes.
BUT, for some reason, addToPrepTimeMinutes is getting set on the DB at 10 or 11 minutes.
It looks like this affects the arrivalTime calculation. I don't see that this is set on the Vendor App, anymore. The client seems to be setting the initial value to 0.
I am digging into this further.

**Comment by vfxdrummer** [comment]
Ok, I think I see what is happening. I think that this is an issue with how addToPrepTime is being handled. Just getting a clear picture of everything.

**Comment by vfxdrummer** [comment]
Yeah, so basically, we used to use addToPrepTime differently.
There is some leftover logic from the old way of doing things.

The new way is straight forward. On the vendor confirmation screen, it uses the default prep time to initialize the value and the vendor can edit it. The result is simply the final 'PrepTime' for the order.
There is no reason to store 'default prep time' and 'add to prep time' separately.
We will just store 'prepTime' and all the math is straightforward. I will clean up the logic.

**Comment by vfxdrummer** [comment]
It also looks like the client is not computing "Your Order Will Be Ready At" correctly.
It looks like it is adding the static prepTime to the currentTime, so it never goes down.
Also, if the initial eta is less than the prepTime, the order should be started immediately.

Looking into these issues....

I also don't see anything in the new code starting the order. Looks like this all needs to be worked out.

**Comment by vfxdrummer** [comment]
Got a PR up, addressing some of these issues : 
https://github.com/DrivingThru/DrivingThruiOS/pull/121/files

**Comment by vfxdrummer** [comment]
So, @danipralea wants me to fix the issues through the rest of the flow before merging.
I only got through order started. I will continue to tweak it in my branch through the rest of order fufillment.

**Comment by siegel86** [comment]
@vfxdrummer I know you are still working behind the scenes, but wanted to log this so you are aware.  
1.  I placed an order from 20 minutes away
2.  The time on the tablet was not counting down with my drive time (i did close the tablet and reopend and it refreshed the time).
3.  The navigation in app is not synced with google maps (i got off freeway and said i had arrived on app...but i was 1/2 mile away)
4.  The order will be ready time was not in sync with arrival time - see pic it was 1:55 but said order would be ready at 2:01 when I had arrived w 0 min drive time:
 
![Image-1](https://user-images.githubusercontent.com/42547181/55359867-c1c8ef00-5487-11e9-8cfe-1f3a9e60f69c.jpg)
5.  The "Im Parked" button would not work when it was 2:01... i had to close out and come back in for it to work.
6.  The order delivered button on the tablet was pressed but on the customer phone the "Delivering" status was stuck not moving to the ratings page.  

Lmk if any of these are not being worked on per your previous comment and i will log those as separate issues.

**Comment by vfxdrummer** [comment]
This should be good, now. Please test.

**Comment by siegel86** [comment]
@vfxdrummer Tablet time is still not counting down.  See pic.   Customer was at store and tablet still said 11 minutes away:
![Image-1](https://user-images.githubusercontent.com/42547181/55503979-acc59a80-5604-11e9-9bcd-e8167e423e8d.jpg)
I clicked on View Map on the order (on top right) and it was still showing me in Calabasas:
![Image-1 (1)](https://user-images.githubusercontent.com/42547181/55504098-f3b39000-5604-11e9-9e57-6ba9f0e75d97.jpg)

**Comment by siegel86** [comment]
@vfxdrummer attached are several simulations done today (see 1-6 on doc below).   The red font indicates glitch and the black is success.   I tried to cover many of the scenarios from ordering from far away and close to changing default prep times and prep times on incoming order.   In general the stage from when the order is placed to arrived has several glitches in the time calculations.   The major glitches are coming from when order are placed from a short distance that are within the Prep Time Window.   On the flip side once arrived and the I'm Parked button shows the transition between phone and tablet is pretty solid.    There's quite a bit here so hopefully you see the themes.   I think you and I getting in the car to simulate should further clarify.  
[DT notes.docx](https://github.com/DrivingThru/DrivingThruiOS/files/3049944/DT.notes.docx)

**Comment by kevinp** [comment]
Great notes @siegel86.  The easier it is to replicate the error state, the quicker these little issues can get knocked out.
