### ISSUE TITLE
Pick up time calculations (shown as time of day) can not be less than the default prep time 

### ISSUE THREAD

**Issue by kevinp** [DrivingThru/DrivingThruiOS#99]
Please note a key feature to be correctly implemented... if I place my order and my driving distance is within  the restaruants meal prep time, the "estimated drive time" should be whatver the actual navigation time is and the "your order will be ready" time should be the mimimum prep time.
![IMG_3840](https://user-images.githubusercontent.com/42547181/54941603-7d1ee000-4eea-11e9-82ed-557fcfc0a35c.jpg)
This picture simulates me placing an order while actually park inside the Dunkin parking lot.   The drive time shoudl be 0 and the time my order is ready is whatever minimum time the restaurant determines either in the setting or this screen, which in this example is 5 minutes:
![IMG_0255](https://user-images.githubusercontent.com/42547181/54941903-34b3f200-4eeb-11e9-8bbe-9093e1d434f7.jpg)

_Originally posted by @siegel86 in https://github.com/DrivingThru/DrivingThruiOS/issues/95#issuecomment-476307269_

**Comment by siegel86** [comment]
Customer shouldn’t be able to press I'm Parked until Arrival time is met and they are parked in designated area.
